# Generated by Django 4.2.3 on 2023-12-06 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('task', models.TextField(blank=True, null=True, verbose_name='Задача')),
                ('date_of_staging', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('importance', models.CharField(choices=[('Важно', 'Важно'), ('Не очень', 'Не очень'), ('Не срочно', 'Не срочно')], default='Не очень', max_length=50, verbose_name='Важность')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
